import{a as w,S as L,i as c}from"./assets/vendor-D8_O3--j.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="41109896-77818a6e9b7c144f2b3908a2d",P="https://pixabay.com/api/";async function m(o,t=1,s=15){const n={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s};return(await w.get(P,{params:n})).data}const E=document.querySelector(".gallery");function $(){E.innerHTML=""}function g(o){const t=document.querySelector(".gallery"),s=o.map(({webformatURL:n,largeImageURL:e,tags:r,likes:a,views:b,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${e}">
            <img src="${n}" alt="${r}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${a}</p>
            <p><b>Views</b> ${b}</p>
            <p><b>Comments</b> ${S}</p>
            <p><b>Downloads</b> ${q}</p>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",s)}const y=15,R=document.querySelector(".form"),B=document.querySelector("input"),u=document.querySelector(".loader"),l=document.querySelector(".load-more"),f=document.querySelector(".end-message");let i=1,d="",p=0;const h=new L(".gallery a",{captionsData:"alt",captionDelay:250});R.addEventListener("submit",async o=>{if(o.preventDefault(),d=B.value.trim(),i=1,d===""){c.warning({message:"Please enter a search term.",position:"topRight"});return}u.style.display="block",l.style.display="none",f.style.display="none",$();try{const t=await m(d,i,y);if(p=t.totalHits,t.hits.length===0){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),i*y<p&&(l.style.display="block");const s=document.querySelector(".gallery-item");if(s){const n=s.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}h.refresh()}catch(t){c.error({message:`Error: ${t.message}`,position:"topRight"})}finally{u.style.display="none"}});l.addEventListener("click",async()=>{i++,u.style.display="block",l.style.display="none";try{const o=await m(d,i,y);g(o.hits),i*y>=p?f.style.display="block":l.style.display="block";const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}h.refresh()}catch(o){c.error({message:`Error: ${o.message}`,position:"topRight"})}finally{u.style.display="none"}});
//# sourceMappingURL=index.js.map
